outputMode: active
scale: 1
background:
  red: 0.0
  green: 0.0
  blue: 0.0
  opacity: 0.9
widget:
  margin:
    margins: [20, 20, 20, 20]
    widget:
      verticalLayout:
        - launcher:
            font_size: 32.0
            length: 1200
            app_opener: "swaymsg exec "
            term_opener: "alacritty -e "
            url_opener: "xdg-open "

